"""
predict_lifespan.py — Lifespan Extension Probability Predictor

Reads a CSV file with columns [Item Name, SMILES], computes molecular
features, and predicts the probability of C. elegans lifespan extension
using the trained Random Forest model.

Usage:
    python predict_lifespan.py --input SMILES_Sample.csv --output predictions.csv

Arguments:
    --input   Path to input CSV (must have 'Item Name' and 'SMILES' columns)
    --output  Path to save prediction results (default: predictions.csv)

Requirements:
    See requirements.txt. The following data files must be in a 'data/'
    subdirectory (generated by the training pipeline):
        data/chemical_descriptors.csv
        data/go_term_features.csv
        data/boruta_selected_features.csv
"""

import argparse
import sys
import time
import requests
import numpy as np
import pandas as pd
from pathlib import Path

from rdkit import Chem
from rdkit.ML.Descriptors.MoleculeDescriptors import MolecularDescriptorCalculator
from sklearn.ensemble import RandomForestClassifier

# ── Config ────────────────────────────────────────────────────────────────────
DATA_DIR   = Path("data")
SLEEP      = 0.2
RANDOM_STATE = 42

CHEMBL_MOL_URL    = "https://www.ebi.ac.uk/chembl/api/data/molecule?pref_name__iexact={}&format=json&limit=1"
CHEMBL_MECH_URL   = "https://www.ebi.ac.uk/chembl/api/data/mechanism?molecule_chembl_id={}&format=json"
CHEMBL_TARGET_URL = "https://www.ebi.ac.uk/chembl/api/data/target/{}?format=json"


# ── Load training data and train model ───────────────────────────────────────
def load_model():
    """
    Load the Boruta-confirmed features from training data and fit
    a final Random Forest on the full labeled dataset.
    Returns: (rf_model, confirmed_chem_features, confirmed_go_features)
    """
    print("Loading training data...")
    chem   = pd.read_csv(DATA_DIR / "chemical_descriptors.csv")
    go     = pd.read_csv(DATA_DIR / "go_term_features.csv")
    boruta = pd.read_csv(DATA_DIR / "boruta_selected_features.csv")

    confirmed = boruta[boruta["status"] == "confirmed"]["feature"].tolist()

    chem_cols = [c for c in chem.columns if c not in ("compound_name", "smiles", "label")]
    go_cols   = [c for c in go.columns   if c not in ("compound_name", "label")]

    merged = chem[["compound_name", "label"] + chem_cols].merge(
        go[["compound_name"] + go_cols], on="compound_name", how="inner"
    )

    all_cols       = chem_cols + go_cols
    confirmed_here = [f for f in confirmed if f in all_cols]
    confirmed_go   = [f for f in confirmed_here if f in go_cols]
    confirmed_chem = [f for f in confirmed_here if f in chem_cols]

    X = merged[confirmed_here].values.astype(float)
    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)
    X = np.clip(X, -1e15, 1e15)
    y = merged["label"].values

    print(f"  Training on {len(y)} compounds "
          f"({(y==1).sum()} pos / {(y==0).sum()} neg)")
    print(f"  Confirmed features: {len(confirmed_chem)} chemical, "
          f"{len(confirmed_go)} GO terms")

    rf = RandomForestClassifier(
        n_estimators=500,
        max_features="sqrt",
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    rf.fit(X, y)
    print("  Model trained.\n")
    return rf, confirmed_chem, confirmed_go


# ── Chemical descriptor computation ──────────────────────────────────────────
def compute_chem_descriptors(smiles: str, feature_names: list) -> dict:
    """Compute RDKit descriptors for a SMILES string."""
    try:
        mol = Chem.MolFromSmiles(str(smiles).strip())
        if mol is None:
            return {f: 0.0 for f in feature_names}
        calc   = MolecularDescriptorCalculator(feature_names)
        values = calc.CalcDescriptors(mol)
        return {
            k: (0.0 if (v is None or not np.isfinite(v)) else float(v))
            for k, v in zip(feature_names, values)
        }
    except Exception:
        return {f: 0.0 for f in feature_names}


# ── GO term lookup ────────────────────────────────────────────────────────────
def fetch_go_terms(name: str, confirmed_go: list) -> dict:
    """Look up ChEMBL targets and extract confirmed GO terms."""
    go_dict = {g: 0 for g in confirmed_go}
    if not confirmed_go:
        return go_dict

    try:
        resp = requests.get(
            CHEMBL_MOL_URL.format(requests.utils.quote(str(name))),
            timeout=10
        )
        mols = resp.json().get("molecules", []) if resp.status_code == 200 else []
        if not mols:
            return go_dict
        chembl_id = mols[0]["molecule_chembl_id"]
        time.sleep(SLEEP)
    except Exception:
        return go_dict

    try:
        resp     = requests.get(CHEMBL_MECH_URL.format(chembl_id), timeout=10)
        mechs    = resp.json().get("mechanisms", []) if resp.status_code == 200 else []
        tids     = [m["target_chembl_id"] for m in mechs if m.get("target_chembl_id")]
        time.sleep(SLEEP)
    except Exception:
        return go_dict

    for tid in tids:
        try:
            resp = requests.get(CHEMBL_TARGET_URL.format(tid), timeout=10)
            if resp.status_code == 200:
                for comp in resp.json().get("target_components", []):
                    for xref in comp.get("target_component_xrefs", []):
                        if xref.get("xref_src_db", "").startswith("Go"):
                            go_name = xref.get("xref_name")
                            if go_name in go_dict:
                                go_dict[go_name] = 1
            time.sleep(SLEEP)
        except Exception:
            continue

    return go_dict


# ── Predict from input CSV ────────────────────────────────────────────────────
def predict(input_path: Path, output_path: Path):
    # ── Load input ────────────────────────────────────────────────────────────
    try:
        df_input = pd.read_csv(input_path)
    except Exception as e:
        print(f"ERROR: Could not read input file: {e}")
        sys.exit(1)

    # Flexible column detection
    name_col   = next((c for c in df_input.columns
                       if c.strip().lower() in ("item name", "name", "compound", "drug")), None)
    smiles_col = next((c for c in df_input.columns
                       if c.strip().lower() in ("smiles", "smiles code", "canonical_smiles")), None)

    if name_col is None or smiles_col is None:
        print(f"ERROR: Could not find name/SMILES columns in {list(df_input.columns)}")
        print("  Expected columns named 'Item Name' (or 'Name'/'Drug') and 'SMILES'.")
        sys.exit(1)

    df_input = df_input[[name_col, smiles_col]].copy()
    df_input.columns = ["name", "smiles"]
    df_input["name"]   = df_input["name"].astype(str).str.strip()
    df_input["smiles"] = df_input["smiles"].astype(str).str.strip()

    print(f"Input: {len(df_input)} compounds from '{input_path}'")

    # ── Train model ───────────────────────────────────────────────────────────
    rf, confirmed_chem, confirmed_go = load_model()

    # ── Score each compound ───────────────────────────────────────────────────
    print(f"Scoring {len(df_input)} compounds...")
    results = []

    for i, row in df_input.iterrows():
        name   = row["name"]
        smiles = row["smiles"]

        print(f"  [{i+1}/{len(df_input)}] {name}", end="", flush=True)

        # Validate SMILES
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            print(f" — invalid SMILES, skipping")
            results.append({
                "item_name":              name,
                "smiles":                 smiles,
                "prob_lifespan_extension": None,
                "prediction":             "invalid SMILES",
                "note":                   "Could not parse SMILES string",
            })
            continue

        # Chemical descriptors
        chem_feats = compute_chem_descriptors(smiles, confirmed_chem)

        # GO term features
        go_feats = fetch_go_terms(name, confirmed_go)

        # Build feature vector
        fvec = np.array(
            [chem_feats.get(f, 0.0) for f in confirmed_chem] +
            [go_feats.get(f, 0)     for f in confirmed_go],
            dtype=float
        )
        fvec = np.nan_to_num(fvec, nan=0.0, posinf=0.0, neginf=0.0)
        fvec = np.clip(fvec, -1e15, 1e15).reshape(1, -1)

        prob = rf.predict_proba(fvec)[0][1]
        pred = "positive" if prob >= 0.5 else "negative"

        print(f" — P = {prob:.3f}  [{pred}]")

        results.append({
            "item_name":               name,
            "smiles":                  smiles,
            "prob_lifespan_extension": round(float(prob), 4),
            "prediction":              pred,
            "note":                    "",
        })

    # ── Save output ───────────────────────────────────────────────────────────
    df_out = pd.DataFrame(results).sort_values(
        "prob_lifespan_extension", ascending=False, na_position="last"
    )
    df_out.to_csv(output_path, index=False)

    # ── Summary ───────────────────────────────────────────────────────────────
    valid = df_out[df_out["prediction"].isin(["positive", "negative"])]
    n_pos = (valid["prediction"] == "positive").sum()
    print(f"\nDone.")
    print(f"  Predicted positive: {n_pos} / {len(valid)}")
    print(f"  Results saved to:   {output_path}")
    print(f"\n{df_out[['item_name','prob_lifespan_extension','prediction']].to_string(index=False)}")


# ── CLI entry point ───────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="Predict C. elegans lifespan extension probability from SMILES."
    )
    parser.add_argument(
        "--input",  "-i",
        required=True,
        help="Input CSV file with 'Item Name' and 'SMILES' columns."
    )
    parser.add_argument(
        "--output", "-o",
        default="predictions.csv",
        help="Output CSV file path (default: predictions.csv)."
    )
    args = parser.parse_args()

    predict(Path(args.input), Path(args.output))


if __name__ == "__main__":
    main()
